name: Prizebond Checker

on:
  workflow_dispatch:
    inputs:
      year:
        description: 'Draw Year'
        required: false
        default: '2023'
      month:
        description: 'Draw Month'
        required: false
        default: '06'
  schedule:
    - cron: "0 0 16,18,20 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Get Current Year and Month
      id: date
      run: |
        echo "year=$(date +'%Y')" >> $GITHUB_OUTPUT
        echo "month=$(date +'%m')" >> $GITHUB_OUTPUT

    - name: Check Prizebond
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        JSON_FILE_URL: ${{ secrets.JSON_FILE_URL }}
        YEAR: ${{ inputs.year || steps.date.outputs.year }}
        MONTH: ${{ inputs.month || steps.date.outputs.month }}
      run: python3 ./main.py --info --send-email
